# Tomcat
server:
  servlet:
    context-path: /boot
  tomcat.:
    max-threads: 1000
    min-spare-threads: 30
    port: 8080
# dev|pro|test 集成 真实 测试
spring:
  profiles:
    active: dev
  mcv:
    view:
      prefix:
      suffix: .html
  #spring cache -redis缓存(目前使用自定义的缓存管理器)
#  cache:
#    type: REDIS
#    cache-names: redisCache
  #Redis
  redis:
    jedis:
      pool:
        min-idle: 5
        max-active: 10
        max-idle: 10
        max-wait: 2000ms
    port: 6379
    host: 127.0.0.1
    timeout: 1000ms
    password:

  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: YByb456137@
    ###################以下为druid增加的配置###########################
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;
druid:
  stat:
    slowSqlMillis: 5000
###############以上为配置druid添加的配置########################################

# Mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yb.pojo
  global-config:
    #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
    id-type: 0
    #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #数据库大写下划线转换
    capital-mode: true
    #刷新mapper 调试神器
    refresh-mapper: true
    # 原生配置
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
  ## jackson
  #spring.jackson.time-zone=GMT+8
  #spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
  #spring.thymeleaf.cache=false
  ## logback
  logging:
    config: classpath:logback-spring.xml
    file: /usr/local/work/log/bootlog.txt